# Generated by Django 3.0.3 on 2020-08-30 20:28

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import search_work_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('search_work_site', '0002_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'Ошибка', 'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AlterField(
            model_name='error',
            name='data',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=search_work_site.models.default_urls)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work_site.City', verbose_name='Город')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work_site.Language', verbose_name='Язык программирования')),
            ],
            options={
                'unique_together': {('city', 'language')},
            },
        ),
    ]
